survey:
    pattern:  /
    defaults: { _controller: "SurveyBundle:Survey:index" }

survey_show:
    pattern:  /{id}/show
    defaults: { _controller: "SurveyBundle:Survey:show" }

survey_new:
    pattern:  /new
    defaults: { _controller: "SurveyBundle:Survey:new" }

survey_create:
    pattern:  /create
    defaults: { _controller: "SurveyBundle:Survey:create" }
    requirements: { _method: post }

survey_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SurveyBundle:Survey:edit" }

survey_update:
    pattern:  /{id}/update
    defaults: { _controller: "SurveyBundle:Survey:update" }
    requirements: { _method: post }

survey_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SurveyBundle:Survey:delete" }
    requirements: { _method: post }
