<?php

namespace Muzej\SurveyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends EntityRepository
{
  public function getTodaySurvey(){
       return $this
                ->createQueryBuilder('e')
                ->addOrderBy('e.time', 'DESC')
                ->andWhere('e.date= :now')
                ->GroupBy('e.name')
                ->setParameter('now', new \DateTime('today'))
                ->getQuery()
                ->execute()
        ;
  }
          
}
