jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
     #   Muzej\UserBundle\Entity\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_USER: [ROLE_SURVEY_ADD, ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SURVEY_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
       # employee_in_database:
       #     entity: { class: UserBundle:User }

    firewalls:
          main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
      
        
#          secured_area:
 #           pattern:    ^/
 #           form_login:
 #               check_path: /login_check
 #               login_path: /login
 #           logout:
 #               path:   /logout
 #               target: /login
 #           anonymous: ~
 #           switch_user: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/survey/new, roles: ROLE_USER }
        - { path: ^/survey/create, roles: ROLE_USER }
        - { path: "^/(\d+)/(edit|update|delete)", roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
