parameters:
#    root_experiment.example.class: Root\ExperimentBundle\Example

services:
#    root_experiment.example:
#        class: %root_experiment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
